param(
    # Optional target Power Platform environment URL.
    # Example: https://bchydro-dev.crm.dynamics.com
    [string]$Environment = "",

    # Power Platform Solution Unique Name, not display name.
    [string]$SolutionName = "AIOnboardingSNReferenceSolution",

    # Temporary zip file generated by export.
    [string]$ZipPath = ".\solution.zip",

    # Folder where the solution will be unpacked for source control.
    [string]$UnpackFolder = ".\solution"
)

function Write-Log {
    param([string]$Message)
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    Write-Host "[$timestamp] $Message"
}

function Write-LogError {
    param([string]$Message)
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    Write-Error "[$timestamp] $Message"
}

Write-Host "========================================"
Write-Host "Power Platform Solution Export Script"
Write-Host "========================================"

Write-Log "Environment: $Environment"
Write-Log "Solution Name: $SolutionName"
Write-Log "Zip Path: $ZipPath"
Write-Log "Unpack Folder: $UnpackFolder"

# Step 1: Authenticate to Power Platform.
# If Environment is provided, authenticate against that environment.
# Otherwise, use the default environment selected by pac.
Write-Log "Authenticating to Power Platform..."

if ([string]::IsNullOrWhiteSpace($Environment)) {
    # Use default environment profile
    pac auth create
} else {
    # Authenticate to specific environment
    pac auth create --environment $Environment
}


if ($LASTEXITCODE -ne 0) {
    Write-LogError "Power Platform authentication failed."
    exit 1
}

# Step 2: Validate that the target solution exists in the current environment.
Write-Log "Validating solution existence..."

$solutions = pac solution list | Out-String

if ($LASTEXITCODE -ne 0) {
    Write-LogError "Unable to list solutions."
    exit 1
}

if ($solutions -notmatch $SolutionName) {
    Write-LogError "Solution '$SolutionName' not found in the current environment."
    Write-Host ""
    Write-Host "Available solutions:"
    pac solution list
    exit 1
}

Write-Log "Solution found."

# Step 3: Remove existing zip file so export can run repeatedly.
Write-Log "Checking existing solution zip..."

if (Test-Path $ZipPath) {
    Write-Log "Existing solution zip found. Removing..."
    Remove-Item $ZipPath -Force
}

# Step 4: Export the solution as unmanaged.
Write-Log "Exporting solution..."

pac solution export `
    --name $SolutionName `
    --path $ZipPath `
    --managed false

if ($LASTEXITCODE -ne 0) {
    Write-LogError "Solution export failed."
    exit 1
}

# Step 5: Remove existing unpacked folder to ensure a clean source-control output.
Write-Log "Cleaning existing unpack folder..."

if (Test-Path $UnpackFolder) {
    Remove-Item $UnpackFolder -Recurse -Force
}

# Step 6: Unpack the exported solution into source-controlled format.
# Note: This PAC version supports --clobber, not --force-overwrite.
Write-Log "Unpacking solution..."

pac solution unpack `
    --zipfile $ZipPath `
    --folder $UnpackFolder `
    --packagetype Unmanaged `
    --clobber

if ($LASTEXITCODE -ne 0) {
    Write-LogError "Solution unpack failed."
    exit 1
}

Write-Log "Export and unpack completed successfully."