param(
    # Optional target Power Platform environment URL.
    # Example: https://bchydro-dev.crm.dynamics.com
    [string]$Environment = "",

    # Temporary zip file generated by pack.
    [string]$ZipPath = ".\solution.zip",

    # Folder containing the unpacked solution files.
    [string]$UnpackFolder = ".\solution"
)

function Write-Log {
    param([string]$Message)
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    Write-Host "[$timestamp] $Message"
}

function Write-LogError {
    param([string]$Message)
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    Write-Error "[$timestamp] $Message"
}

Write-Host "========================================"
Write-Host "Power Platform Solution Import Script"
Write-Host "========================================"

Write-Log "Environment: $Environment"
Write-Log "Zip Path: $ZipPath"
Write-Log "Unpack Folder: $UnpackFolder"

# Warning: This operation will deploy to the target environment
Write-Log "WARNING: This will import the solution into the selected Power Platform environment."

# Step 1: Validate that the unpacked solution folder exists.
Write-Log "Validating unpack folder..."

if (-not (Test-Path $UnpackFolder)) {
    Write-LogError "Unpack folder '$UnpackFolder' does not exist."
    exit 1
}

# Step 2: Authenticate to Power Platform.
# If Environment is provided, authenticate against that environment.
# Otherwise, use the default environment selected by pac.
Write-Log "Authenticating to Power Platform..."

if ([string]::IsNullOrWhiteSpace($Environment)) {
    pac auth create
} else {
    pac auth create --environment $Environment
}

if ($LASTEXITCODE -ne 0) {
    Write-LogError "Power Platform authentication failed."
    exit 1
}

# Step 3: Remove existing zip file so pack can run repeatedly.
Write-Log "Checking existing solution zip..."

if (Test-Path $ZipPath) {
    Write-Log "Existing solution zip found. Removing..."
    Remove-Item $ZipPath -Force
}

# Step 4: Pack the unpacked solution folder into a deployable zip.
Write-Log "Packing solution..."

pac solution pack `
    --folder $UnpackFolder `
    --zipfile $ZipPath `
    --packagetype Unmanaged

if ($LASTEXITCODE -ne 0) {
    Write-LogError "Solution pack failed."
    exit 1
}

# Step 5: Import the packed solution into the selected environment and publish changes.
Write-Log "Importing solution into the selected environment..."
Write-Log "WARNING: This will update the target Power Platform environment."

pac solution import `
    --path $ZipPath `
    --publish-changes

if ($LASTEXITCODE -ne 0) {
    Write-LogError "Solution import failed."
    exit 1
}

Write-Log "Import completed successfully."